version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Authenticate to Quay
          command: |
            docker login -u="${QUAY_USER}" -p="${QUAY_TOKEN}" quay.io
      - run:
          name: Build image
          command: |
            docker build -t ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .
      - run:
          name: Tag and push image
          command: |
            docker tag ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} quay.io/dcondomitti/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
            docker push quay.io/dcondomitti/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
            docker tag ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} quay.io/dcondomitti/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}
            docker push quay.io/dcondomitti/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}
      - run:
          name: Echo images
          command: |
            echo quay.io/dcondomitti/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
            echo quay.io/dcondomitti/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          context: quay
